name: conference_2023
description: FlutterKaigi 2023 official application.
publish_to: 'none'
version: 1.5.0+22

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  intl: any

  cupertino_icons: ^1.0.0

  # annotation
  freezed_annotation: ^2.0.0
  json_annotation: ^4.9.0
  riverpod_annotation: ^2.0.0

  # firebase
  firebase_core: ^3.0.0
  firebase_crashlytics: ^4.0.0
  firebase_messaging: ^15.0.0
  firebase_remote_config: ^5.0.0

  flutter_riverpod: ^2.0.0
  go_router: ^14.0.0

  adaptive_dialog: ^2.0.0
  add_2_calendar: ^3.0.0
  auto_size_text: ^3.0.0
  cached_network_image: ^3.0.0
  collection: ^1.0.0
  dynamic_color: ^1.0.0
  flutter_linkify: ^6.0.0
  flutter_local_notifications: ^17.0.0
  flutter_markdown: ^0.7.0
  flutter_svg: ^2.0.0
  gap: ^3.0.0
  google_fonts: ^6.0.0
  google_static_maps_controller: ^1.0.0
  permission_handler: ^11.0.0
  shared_preferences: ^2.0.0
  two_dimensional_scrollables: ^0.2.0
  url_launcher: ^6.0.0
  visibility_detector: ^0.4.0

  accessibility_tools: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  custom_lint: ^0.6.0
  riverpod_lint: ^2.0.0

  build_runner: ^2.0.0
  freezed: ^2.0.0
  json_serializable: ^6.0.0
  riverpod_generator: ^2.0.0
  flutter_gen_runner: ^5.0.0
  go_router_builder: ^2.0.0
  flutter_launcher_icons: ^0.13.0

flutter_gen:
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true

  assets:
    - assets/svg/
