name: Deploy flutter web application

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3
      - run: echo ${{ secrets.FIREBASE_OPTIONS_WEB_PRO }} | base64 -di | tee firebase_options_web_pro.dart lib/util/web/firebase_options_web_pro.dart >/dev/null
      - uses: subosito/flutter-action@v2
        with:
          channel: 'beta'
          cache: true
      - run: flutter pub get
      - run: flutter build web --dart-define-from-file=dart_defines/pro.json --base-href "/conference-app-2023/" 
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
