name: PR review

on:
  pull_request:

jobs:
  analyze:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'beta'
          cache: true
      - run: flutter pub get
      - uses: invertase/github-action-dart-analyzer@v2.0.0

  check:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'beta'
          cache: true
      - run: flutter pub get
      - run: dart format --output=none --set-exit-if-changed .
      - run: flutter test

  build_web_preview:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'beta'
          cache: true
      - run: flutter pub get
      - run: flutter build web --dart-define-from-file=dart_defines/dev.json

      - uses: actions/upload-artifact@v3
        with:
          name: pr
          path: |
            firebase.json
            build/
